apiVersion: apps/v1
kind: Deployment
metadata:
  name: user01-order
  labels:
    app: user01-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user01-order
  template:
    metadata:
      labels:
        app: user01-order
    spec:
      containers:
        - name: user01-order
          image: username/order:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
          env:
            - name: ORDERED_TOPIC
              valueFrom:
                configMapKeyRef:
                   name: localfood-topic
                   key: ORDERED_TOPIC
